### ISSUE TITLE
[Feature Request] Toggle for launch on startup

### ISSUE THREAD

**Issue by horizon3902** [Sunehildeep/customfans-helios#1]

**Comment by Sunehildeep** [comment]
Will add it soon

**Comment by Sunehildeep** [comment]
Done

**Comment by epe** [comment]
Can you specify if this is for the helios NAS with ARM CPU ? 
Its totally unclear from your Readme file.

**Comment by Sunehildeep** [comment]
> Can you specify if this is for the helios NAS with ARM CPU ? Its totally unclear from your Readme file.

This might not be what you are looking for. This one is for Acer Predator Helios. Updated the readme to include the brand
